### ISSUE TITLE
We have provided our Aspera share to our clients and they are trying to download and upload the data to the shares through CLI and find error and Failure. 

### ISSUE THREAD

**Issue by xavierv79** [IBM/aspera-cli#127]
`D:\Aspera\Download_utility-1.1\Repository\build>ant run
Picked up JAVA_TOOL_OPTIONS: -Dfile.encoding=UTF-8
Buildfile: D:\Aspera\Download_utility-1.1\Repository\build\build.xml

run:
[asperadownload] log4j: reset attribute= "false".
[asperadownload] log4j: Threshold ="null".
[asperadownload] log4j: Level value for root is  [debug].
[asperadownload] log4j: root level set to DEBUG
[asperadownload] log4j: Class name: [org.apache.log4j.ConsoleAppender]
[asperadownload] log4j: Setting property [target] to [System.out].
[asperadownload] log4j: Parsing layout of class: "org.apache.log4j.PatternLayout"
[asperadownload] log4j: Setting property [conversionPattern] to [%d{yyyy-MM-dd HH:mm:ss} %-5p %c{1}:%L - %m%n].
[asperadownload] log4j: Adding appender named [console] to category [root].
[asperadownload] log4j: Class name: [org.apache.log4j.RollingFileAppender]
[asperadownload] log4j: Setting property [file] to [AsperaUtility.log].
[asperadownload] log4j: Parsing layout of class: "org.apache.log4j.PatternLayout"
[asperadownload] log4j: Setting property [conversionPattern] to [%d{yyyy-MM-dd HH:mm:ss} %-5p %c{1}:%L - %m%n].
[asperadownload] log4j: setFile called: AsperaUtility.log, true
[asperadownload] log4j: setFile ended
[asperadownload] log4j: Adding appender named [fileAppender] to category [root].
[asperadownload] 2023-10-09 11:33:25 INFO  AsperaUploadTask:87 - In Aspera Tool Execute Starts
[asperadownload] 2023-10-09 11:33:25 INFO  AsperaUploadTask:55 - loading conf/templates.properties property file
[asperadownload] 2023-10-09 11:33:25 INFO  AsperaUploadTask:55 - loading conf/configuration.properties property file
[asperadownload] 2023-10-09 11:33:25 INFO  AsperaUtil:76 - >Starting [{DOWNLOAD}]
[asperadownload] 2023-10-09 11:33:25 DEBUG TransferParameterUtility:62 - URL:[{https://esd.finastra.com/node_api/files/download_setup}], asperaUser:[{cacib.fgpp}], asperaPassword:[{Check the build script...}] sources:[{[Ljava.lang.String;@491666ad}] destinations:[{[Ljava.lang.String;@176d53b2}]
[asperadownload] 2023-10-09 11:33:25 DEBUG TransferParameterUtility:83 - initialise...
[asperadownload] 2023-10-09 11:33:26 DEBUG RequestAddCookies:122 - CookieSpec selected: default
[asperadownload] 2023-10-09 11:33:26 DEBUG RequestAuthCache:76 - Auth cache not set in the context
[asperadownload] 2023-10-09 11:33:26 DEBUG PoolingHttpClientConnectionManager:249 - Connection request: [route: {s}->https://esd.finastra.com:443][total kept alive: 0; route allocated: 0 of 2; total allocated: 0 of 20]
[asperadownload] 2023-10-09 11:33:26 DEBUG PoolingHttpClientConnectionManager:282 - Connection leased: [id: 0][route: {s}->https://esd.finastra.com:443][total kept alive: 0; route allocated: 1 of 2; total allocated: 1 of 20]
[asperadownload] 2023-10-09 11:33:26 DEBUG MainClientExec:234 - Opening connection {s}->https://esd.finastra.com:443
[asperadownload] 2023-10-09 11:33:26 DEBUG DefaultManagedHttpClientConnection:87 - http-outgoing-0: Shutdown connection
[asperadownload] 2023-10-09 11:33:26 DEBUG MainClientExec:128 - Connection discarded
[asperadownload] 2023-10-09 11:33:26 DEBUG DefaultManagedHttpClientConnection:79 - http-outgoing-0: Close connection
[asperadownload] 2023-10-09 11:33:26 DEBUG PoolingHttpClientConnectionManager:320 - Connection released: [id: 0][route: {s}->https://esd.finastra.com:443][total kept alive: 0; route allocated: 0 of 2; total allocated: 0 of 20]
[asperadownload] 2023-10-09 11:33:26 DEBUG PoolingHttpClientConnectionManager:388 - Connection manager is shutting down
[asperadownload] 2023-10-09 11:33:26 DEBUG PoolingHttpClientConnectionManager:394 - Connection manager shut down
[asperadownload] 2023-10-09 11:33:26 ERROR AsperaUploadTask:196 - Transfer Failed!
[asperadownload] 2023-10-09 11:33:26 ERROR AsperaUploadTask:197 - Error : [Ljava.lang.StackTraceElement;@3cc1435c

BUILD FAILED
D:\Aspera\Download_utility-1.1\Repository\build\build.xml:18: com.misys.bachuleon.asperadelivery.utilities.AsperaUtilityException: Cannot execute HTTPClient!
        at com.misys.bachuleon.asperadelivery.utilities.TransferParameterUtility.execute(TransferParameterUtility.java:171)
        at com.misys.bachuleon.asperadelivery.utilities.TransferParameterUtility.getTransferParameters(TransferParameterUtility.java:66)
        at com.misys.bachuleon.asperadelivery.utilities.AsperaUtil.startTransfer(AsperaUtil.java:79)
        at com.misys.bachuleon.autodelivery.AsperaUploadTask.downloadFile(AsperaUploadTask.java:260)
        at com.misys.bachuleon.autodelivery.AsperaUploadTask.execute(AsperaUploadTask.java:191)
        at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:299)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:99)
        at org.apache.tools.ant.Task.perform(Task.java:350)
        at org.apache.tools.ant.Target.execute(Target.java:449)
        at org.apache.tools.ant.Target.performTasks(Target.java:470)
        at org.apache.tools.ant.Project.executeSortedTargets(Project.java:1401)
        at org.apache.tools.ant.Project.executeTarget(Project.java:1374)
        at org.apache.tools.ant.helper.DefaultExecutor.executeTargets(DefaultExecutor.java:41)
        at org.apache.tools.ant.Project.executeTargets(Project.java:1264)
        at org.apache.tools.ant.Main.runBuild(Main.java:818)
        at org.apache.tools.ant.Main.startAnt(Main.java:223)
        at org.apache.tools.ant.launch.Launcher.run(Launcher.java:284)
        at org.apache.tools.ant.launch.Launcher.main(Launcher.java:101)
Caused by: java.net.UnknownHostException: esd.finastra.com
        at java.net.Inet6AddressImpl.lookupAllHostAddr(Native Method)
        at java.net.InetAddress$2.lookupAllHostAddr(InetAddress.java:928)
        at java.net.InetAddress.getAddressesFromNameService(InetAddress.java:1323)
        at java.net.InetAddress.getAllByName0(InetAddress.java:1276)
        at java.net.InetAddress.getAllByName(InetAddress.java:1192)
        at java.net.InetAddress.getAllByName(InetAddress.java:1126)
        at org.apache.http.impl.conn.SystemDefaultDnsResolver.resolve(SystemDefaultDnsResolver.java:45)
        at org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:111)
        at org.apache.http.impl.conn.PoolingHttpClientConnectionManager.connect(PoolingHttpClientConnectionManager.java:353)
        at org.apache.http.impl.execchain.MainClientExec.establishRoute(MainClientExec.java:380)
        at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:236)
        at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:184)
        at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:88)
        at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:110)
        at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:184)
        at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:82)
        at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:107)
        at com.misys.bachuleon.asperadelivery.utilities.TransferParameterUtility.execute(TransferParameterUtility.java:165)
        ... 21 more

Total time: 0 seconds
`

**Comment by laurent-martin** [comment]
That seems to be a java client app, not related to `ascli` ?

**Comment by xavierv79** [comment]
Team is using the below API configuration
`#Aspera client installation location full path with file name(ascp.exe).
#for windows ascp.exe is available in package (Repository/bin) location.
aspera.client=D:\Aspera\Download_utility-1.1\Repository\bin\ascp.exe
#Aspera private key location for node server
aspera.node.private.key=D:\Aspera\private\Aspera_Utility_Private_key
#full path to the private key file location for share server aspera.share.private.key=<full path to private key>
#aspera frontend username – User should have permission to upload and create share.
aspera.share.username= 
#aspera frontend password (Encrypted)
aspera.share.passphrase= 
#local (full) path to download file/folder from Aspera.
#The path should be existing to download files from Aspera.
destination.location=D:\Aspera\Downloads 
#Aspera sharename from which share the file/folder has to be downloaded.
#folder inside a share also can be downloaded. Share and the folder should be available in Aspera.
source.location=
#file/folder should get overwrite or not configuration.
#options are 
1. ALWAYS - Over write every time if file/folder already exist.
2. NEVER  - Do not over write if the file/folder already exist.
3. OLDER  - Over write only if the file/folder is older than the source.
file.overwrite=ALWAYS
#proxy server details for HTTP fallback. 
#Only if the port 33001 port is blocked.
proxy_host= 
proxy_port=8080
#aspera username list to get the permission to download
##aspera.users=user1,user2
#aspera group list to get the permission to download
##aspera.groups=group1,group2
#should I bypass the checksum verification
bypass.checksum=false
#Create share or not for the uploaded folder
share.create=true
direction=DOWNLOAD

#List of Properties with Constant values (Please do not change without guidance)
#Aspera download setup url
api.download=https://esd.finastra.com/node_api/files/download_setup
#Aspera upload setup url
api.upload=https://esd.finastra.com/node_api/files/upload_setup
#Aspera node server name
aspera.node.hostname=esdstore2.finastra.com
#Aspera node server username default is transfer
aspera.node.username=transfer
#aspera share server name
aspera.share.hostname=esd.finastra.com

`
Please guide how to resolve this issue.

**Comment by laurent-martin** [comment]
Please reach out : laurent.martin.aspera@fr.ibm.com

**Comment by xavierv79** [comment]
Do we need to send mail to [laurent.martin.aspera@fr.ibm.com] regarding this.

**Comment by laurent-martin** [comment]
For proper support, contact the IBM support.

I removed your logs from that ticket, because this is an open source tool, and information here is public.

You can reach me tomorrow to look at this, but I am not in support.

**Comment by xavierv79** [comment]
Thank you

**Comment by xavierv79** [comment]
Thanks for your support.
