### ISSUE TITLE
Error running the ascli config wizard command

### ISSUE THREAD

**Issue by MikeKenno** [IBM/aspera-cli#132]
When running the wizard command we're getting the following issue after entering a url

```
from C:/Users/usr/Ruby/bin/ascli:23:in `<main>'
        14: from C:/Users/usr/Ruby/bin/ascli:23:in `load'
        13: from C:/Users/usr/Ruby/lib/ruby/gems/2.7.0/gems/aspera-cli-4.15.0/bin/ascli:38:in `<top (required)>'
        12: from C:/Users/usr/Ruby/lib/ruby/gems/2.7.0/gems/aspera-cli-4.15.0/lib/aspera/cli/main.rb:287:in `process_command_line'
        11: from C:/Users/usr/Ruby/lib/ruby/gems/2.7.0/gems/aspera-cli-4.15.0/lib/aspera/cli/plugins/config.rb:979:in `execute_action'
        10: from C:/Users/usr/Ruby/lib/ruby/gems/2.7.0/gems/aspera-cli-4.15.0/lib/aspera/cli/plugins/config.rb:629:in `identify_plugins_for_url'
         9: from C:/Users/usr/Ruby/lib/ruby/gems/2.7.0/gems/aspera-cli-4.15.0/lib/aspera/cli/plugins/config.rb:629:in `each'
         8: from C:/Users/usr/Ruby/lib/ruby/gems/2.7.0/gems/aspera-cli-4.15.0/lib/aspera/cli/plugins/config.rb:634:in `block in identify_plugins_for_url'
         7: from C:/Users/usr/Ruby/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:83:in `require'
         6: from C:/Users/usr/Ruby/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:83:in `require'
         5: from C:/Users/usr/Ruby/lib/ruby/gems/2.7.0/gems/aspera-cli-4.15.0/lib/aspera/cli/plugins/preview.rb:9:in `<top (required)>'
         4: from C:/Users/usr/Ruby/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:83:in `require'
         3: from C:/Users/usr/Ruby/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:83:in `require'
         2: from C:/Users/usr/Ruby/lib/ruby/gems/2.7.0/gems/aspera-cli-4.15.0/lib/aspera/preview/terminal.rb:5:in `<top (required)>'
         1: from C:/Users/usr/Ruby/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:83:in `require'
C:/Users/usr/Ruby/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:83:in `require': cannot load such file -- rmagick (LoadError)
```

**Comment by laurent-martin** [comment]
There are several ways to avoid this problem, that should be fixed in next version.

You can try **ONE** of the following methods, in order of difficulty:

1. when executing the wizard, specify the expected application:
  `ascli conf wizard eudemo.asperademo.com faspex5`
2. or, patch the faulty source:
    - execute `ascli conf gem path` : it displays a folder path, go to this folder.
    - inside this folder, edit the file : `aspera/cli/plugins/preview.rb`
    - remove (or comment-out with a `#`) the line near beginning: `require 'aspera/preview/terminal'`
3. or, Install the missing gem: `gem install rmagick`
4. or, install the beta from : https://ibm.biz/aspera-cli-beta

**Comment by laurent-martin** [comment]
4.16 should fix this
