### ISSUE TITLE
wss transfer failing

### ISSUE THREAD

**Issue by dremerten** [IBM/aspera-cli#134]
Hi @laurent-martin
I'm getting an error sending to a wss hsts. Maybe I'm missing something?

```
{
  "cookie": "aspera.faspex20:u:2dd720a9-6d9e-45c4-ab3a-1c012b80bcdf:YW5kcmUubWVydGVuQGlibS5jb20:eyJfcGtnX3V1aWQiOiI0MzczM2MyMC0xZjg5LTQ5MDctYmUxOC0yZGQ0N2JjMmFmN2IiLCJfcGtnX25hbWUiOiJQZXJmb3JtYW5jZS1UZXN0LTE4OTU4LTIwMjQtMDItMDgtVVRDLVRJTUUtMjA6NDQ6NTIiLCJfY3JlYXRlZF91dGMiOiIyMDI0LTAyLTA4VDIwOjQ0OjUzLjA4MFoiLCJfZHJvcGJveF9uYW1lIjoiUGVyZl9UZXN0cyJ9:UGVyZm9ybWFuY2UtVGVzdC0xODk1OC0yMDI0LTAyLTA4LVVUQy1USU1FLTIwOjQ0OjUy",
  "target_rate_kbps": 500000,
  "create_dir": true,
  "lock_rate_policy": true,
  "lock_min_rate": true,
  "target_rate_cap_kbps": 500000,
  "tags": {
    "aspera": {
      "faspex": {
        "f5_xfer_id": "2dd720a9-6d9e-45c4-ab3a-1c012b80bcdf",
        "num_recipients": 1,
        "dropbox": "Perf_Tests",
        "recipients": {
        },
        "metadata": {
          "_pkg_uuid": "43733c20-1f89-4907-be18-2dd47bc2af7b",
          "_pkg_name": "Performance-Test-18958-2024-02-08-UTC-TIME-20:44:52",
          "_created_utc": "2024-02-08T20:44:53.080Z",
          "_dropbox_name": "Perf_Tests"
        },
        "_pkg_id": 10917
      }
    }
  },
  "destination_root": "/Performance-Test-18958-2024-02-08-UTC-TIME-20_44_52 - 43733c20-1f89-4907-be18-2dd47bc2af7b.aspera-package/PKG - Performance-Test-18958-2024-02-08-UTC-TIME-20_44_52/",
  "token": "🔑",
  "direction": "send",
  "cipher": "aes-256-gcm",
  "rate_policy_allowed": "fixed",
  "rate_policy": "fair",
  "min_rate_cap_kbps": 0,
  "min_rate_kbps": 0,
  "remote_host": "wss-hsts443.asperaqa.us",
  "remote_user": "faspex",
  "ssh_port": 33001,
  "fasp_port": 33001,
  "wss_enabled": true,
  "wss_port": 443,
  "authentication": "token",
  "multi_session": 0
}
D, [2024-02-08T20:44:53.672238 #2509891] DEBUG -- : result: code=201
D, [2024-02-08T20:44:53.672273 #2509891] DEBUG -- : raise_on_error POST /aspera/faspex/api/v5/packages/10917/transfer_spec/upload?transfer_type=connect 201
D, [2024-02-08T20:44:53.672387 #2509891] DEBUG -- : result={:http=>#<Net::HTTPCreated 201 Created readbody=true>, :data=>{"cookie"=>"aspera.faspex20:u:2dd720a9-6d9e-45c4-ab3a-1c012b80bcdf:YW5kcmUubWVydGVuQGlibS5jb20:eyJfcGtnX3V1aWQiOiI0MzczM2MyMC0xZjg5LTQ5MDctYmUxOC0yZGQ0N2JjMmFmN2IiLCJfcGtnX25hbWUiOiJQZXJmb3JtYW5jZS1UZXN0LTE4OTU4LTIwMjQtMDItMDgtVVRDLVRJTUUtMjA6NDQ6NTIiLCJfY3JlYXRlZF91dGMiOiIyMDI0LTAyLTA4VDIwOjQ0OjUzLjA4MFoiLCJfZHJvcGJveF9uYW1lIjoiUGVyZl9UZXN0cyJ9:UGVyZm9ybWFuY2UtVGVzdC0xODk1OC0yMDI0LTAyLTA4LVVUQy1USU1FLTIwOjQ0OjUy", "target_rate_kbps"=>500000, "create_dir"=>true, "lock_rate_policy"=>true, "lock_min_rate"=>true, "target_rate_cap_kbps"=>500000, "tags"=>{"aspera"=>{"faspex"=>{"f5_xfer_id"=>"2dd720a9-6d9e-45c4-ab3a-1c012b80bcdf", "num_recipients"=>1, "dropbox"=>"Perf_Tests", "recipients"=>{}, "metadata"=>{"_pkg_uuid"=>"43733c20-1f89-4907-be18-2dd47bc2af7b", "_pkg_name"=>"Performance-Test-18958-2024-02-08-UTC-TIME-20:44:52", "_created_utc"=>"2024-02-08T20:44:53.080Z", "_dropbox_name"=>"Perf_Tests"}, "_pkg_id"=>10917}}}, "destination_root"=>"/Performance-Test-18958-2024-02-08-UTC-TIME-20_44_52 - 43733c20-1f89-4907-be18-2dd47bc2af7b.aspera-package/PKG - Performance-Test-18958-2024-02-08-UTC-TIME-20_44_52/", "token"=>"🔑", "direction"=>"send", "cipher"=>"aes-256-gcm", "rate_policy_allowed"=>"fixed", "rate_policy"=>"fair", "min_rate_cap_kbps"=>0, "min_rate_kbps"=>0, "remote_host"=>"wss-hsts443.asperaqa.us", "remote_user"=>"faspex", "ssh_port"=>33001, "fasp_port"=>33001, "wss_enabled"=>true, "wss_port"=>443, "authentication"=>"token", "multi_session"=>0}}
D, [2024-02-08T20:44:53.672905 #2509891] DEBUG -- : (value) get transfer=direct
D, [2024-02-08T20:44:53.676629 #2509891] DEBUG -- : (accessor) get transfer_info={}
D, [2024-02-08T20:44:53.676766 #2509891] DEBUG -- : agent_options (json)=
{
  "quiet": true,
  "check_ignore": "#<Proc:0x00007f397ef2e068 /usr/local/rvm/gems/ruby-3.1.2/gems/aspera-cli-4.15.0/lib/aspera/cli/transfer_agent.rb:113 (lambda)>",
  "trusted_certs": [

  ],
  "progress": null
}
D, [2024-02-08T20:44:53.676900 #2509891] DEBUG -- : resume params={:iter_max=>7, :sleep_initial=>2, :sleep_factor=>2, :sleep_max=>60}
D, [2024-02-08T20:44:53.676982 #2509891] DEBUG -- : agent_options (json)=
{
  "quiet": true,
  "check_ignore": "#<Proc:0x00007f397ef2e068 /usr/local/rvm/gems/ruby-3.1.2/gems/aspera-cli-4.15.0/lib/aspera/cli/transfer_agent.rb:113 (lambda)>",
  "trusted_certs": [

  ],
  "spawn_timeout_sec": 3,
  "spawn_delay_sec": 2,
  "wss": true,
  "multi_incr_udp": true,
  "resume": {
  },
  "ascp_args": [

  ]
}
D, [2024-02-08T20:44:53.677084 #2509891] DEBUG -- : transfer agent is a Aspera::Fasp::AgentDirect
D, [2024-02-08T20:44:53.677188 #2509891] DEBUG -- : xfer id=
D, [2024-02-08T20:44:53.677254 #2509891] DEBUG -- : ts (json)=
{
  "cookie": "aspera.faspex20:u:2dd720a9-6d9e-45c4-ab3a-1c012b80bcdf:YW5kcmUubWVydGVuQGlibS5jb20:eyJfcGtnX3V1aWQiOiI0MzczM2MyMC0xZjg5LTQ5MDctYmUxOC0yZGQ0N2JjMmFmN2IiLCJfcGtnX25hbWUiOiJQZXJmb3JtYW5jZS1UZXN0LTE4OTU4LTIwMjQtMDItMDgtVVRDLVRJTUUtMjA6NDQ6NTIiLCJfY3JlYXRlZF91dGMiOiIyMDI0LTAyLTA4VDIwOjQ0OjUzLjA4MFoiLCJfZHJvcGJveF9uYW1lIjoiUGVyZl9UZXN0cyJ9:UGVyZm9ybWFuY2UtVGVzdC0xODk1OC0yMDI0LTAyLTA4LVVUQy1USU1FLTIwOjQ0OjUy",
  "target_rate_kbps": 500000,
  "create_dir": true,
  "lock_rate_policy": true,
  "lock_min_rate": true,
  "target_rate_cap_kbps": 500000,
  "tags": {
    "aspera": {
      "faspex": {
        "f5_xfer_id": "2dd720a9-6d9e-45c4-ab3a-1c012b80bcdf",
        "num_recipients": 1,
        "dropbox": "Perf_Tests",
        "recipients": {
        },
        "metadata": {
          "_pkg_uuid": "43733c20-1f89-4907-be18-2dd47bc2af7b",
          "_pkg_name": "Performance-Test-18958-2024-02-08-UTC-TIME-20:44:52",
          "_created_utc": "2024-02-08T20:44:53.080Z",
          "_dropbox_name": "Perf_Tests"
        },
        "_pkg_id": 10917
      },
      "xfer_id": "34a88ce6-7035-4bf3-a0c0-1ab7cdc6b434",
      "xfer_retry": 3600
    }
  },
  "destination_root": "/Performance-Test-18958-2024-02-08-UTC-TIME-20_44_52 - 43733c20-1f89-4907-be18-2dd47bc2af7b.aspera-package/PKG - Performance-Test-18958-2024-02-08-UTC-TIME-20_44_52/",
  "token": "🔑",
  "direction": "send",
  "cipher": "aes-256-gcm",
  "rate_policy_allowed": "fixed",
  "rate_policy": "fair",
  "min_rate_cap_kbps": 0,
  "min_rate_kbps": 0,
  "remote_host": "wss-hsts443.asperaqa.us",
  "remote_user": "faspex",
  "ssh_port": 33001,
  "fasp_port": 33001,
  "wss_enabled": true,
  "wss_port": 443,
  "multi_session": 0,
  "paths": [
    {
      "source": "data_5206"
    }
  ]
}
D, [2024-02-08T20:44:53.677789 #2509891] DEBUG -- : multi_session count is zero: no multi session
D, [2024-02-08T20:44:53.677853 #2509891] DEBUG -- : parameters_options (json)=
{
  "ascp_args": [

  ],
  "wss": true,
  "check_ignore": "#<Proc:0x00007f397ef2e068 /usr/local/rvm/gems/ruby-3.1.2/gems/aspera-cli-4.15.0/lib/aspera/cli/transfer_agent.rb:113 (lambda)>",
  "quiet": true
}
D, [2024-02-08T20:44:53.677973 #2509891] DEBUG -- : ignore cert? ["wss-hsts443.asperaqa.us", 443]
ERROR: Other(NoMethodError): undefined method `each' for nil:NilClass

            @options[:trusted_certs].each do |file|
                                    ^^^^^
/usr/local/rvm/gems/ruby-3.1.2/gems/aspera-cli-4.15.0/lib/aspera/fasp/parameters.rb:223:in `ascp_args': undefined method `each' for nil:NilClass (NoMethodError)

            @options[:trusted_certs].each do |file|
                                    ^^^^^
	from /usr/local/rvm/gems/ruby-3.1.2/gems/aspera-cli-4.15.0/lib/aspera/fasp/agent_direct.rb:81:in `start_transfer'
	from /usr/local/rvm/gems/ruby-3.1.2/gems/aspera-cli-4.15.0/lib/aspera/cli/transfer_agent.rb:229:in `start'
	from /usr/local/rvm/gems/ruby-3.1.2/gems/aspera-cli-4.15.0/lib/aspera/cli/plugins/faspex5.rb:431:in `package_action'
	from /usr/local/rvm/gems/ruby-3.1.2/gems/aspera-cli-4.15.0/lib/aspera/cli/plugins/faspex5.rb:489:in `execute_action'
	from /usr/local/rvm/gems/ruby-3.1.2/gems/aspera-cli-4.15.0/lib/aspera/cli/main.rb:287:in `process_command_line'
	from /usr/local/rvm/gems/ruby-3.1.2/gems/aspera-cli-4.15.0/bin/ascli:38:in `<top (required)>'
	from /usr/local/rvm/gems/ruby-3.1.2/bin/ascli:25:in `load'
	from /usr/local/rvm/gems/ruby-3.1.2/bin/ascli:25:in `<main>'
	from /usr/local/rvm/gems/ruby-3.1.2/bin/ruby_executable_hooks:22:in `eval'
	from /usr/local/rvm/gems/ruby-3.1.2/bin/ruby_executable_hooks:22:in `<main>'
Transfer complete
^C
root@aws-ascli-prod:~# cat /tmp/faspex5_script/ascli-ha-manual.log | grep ascli
/root/ascli_send_packages_prod_ha.sh: line 71: /root/.aspera/ascli/etc/ascli-bashrc.sh: No such file or directory
D, [2024-02-08T20:44:52.953698 #2509891] DEBUG -- : (accessor/default) set home=/root/.aspera/ascli
D, [2024-02-08T20:44:52.954010 #2509891] DEBUG -- : ascli folder: /root/.aspera/ascli
D, [2024-02-08T20:44:52.954050 #2509891] DEBUG -- : persistency folder: /root/.aspera/ascli/persist_store
D, [2024-02-08T20:44:52.954373 #2509891] DEBUG -- : (accessor/default) set config_file=/root/.aspera/ascli/config.yaml
D, [2024-02-08T20:44:52.954690 #2509891] DEBUG -- : config file is: /root/.aspera/ascli/config.yaml
D, [2024-02-08T20:44:52.954742 #2509891] DEBUG -- : loading /root/.aspera/ascli/config.yaml
  "f5-ha-prod-ascli": {
    "faspex5": "f5-ha-prod-ascli"
D, [2024-02-08T20:44:52.967716 #2509891] DEBUG -- : persistency: {:manager=>#<Aspera::PersistencyFolder:0x00007f397f937118 @cache={}, @folder="/root/.aspera/ascli/persist_store">, :data=>[], :id=>"version_last_check"}
D, [2024-02-08T20:44:52.967868 #2509891] DEBUG -- : persistency = /root/.aspera/ascli/persist_store/version_last_check.txt
D, [2024-02-08T20:44:52.977054 #2509891] DEBUG -- : add_plugin_default_preset:faspex5:f5-ha-prod-ascli
D, [2024-02-08T20:44:52.985856 #2509891] DEBUG -- : persistency = /root/.aspera/ascli/persist_store/token_faspex5-dev_asperaqa_us_jwt_user_andre_merten@ibm_com.txt
D, [2024-02-08T20:44:52.986833 #2509891] DEBUG -- : call_data = {:base_url=>"https://faspex5-dev.asperaqa.us/aspera/faspex/api/v5", :auth=>{:type=>:oauth2, :base_url=>"https://faspex5-dev.asperaqa.us/aspera/faspex/auth", :grant_method=>:jwt, :client_id=>"766b98ff-64e7-4f09-983e-95009024d29b", :jwt=>{:payload=>{:iss=>"766b98ff-64e7-4f09-983e-95009024d29b", :aud=>"766b98ff-64e7-4f09-983e-95009024d29b", :sub=>"user:andre.merten@ibm.com"}, :private_key_obj=>#<OpenSSL::PKey::RSA:0x00007f397ef71250 oid=rsaEncryption>, :headers=>{:typ=>"JWT"}}}, :not_auth_codes=>["401"], :operation=>"POST", :subpath=>"packages", :headers=>{"Accept"=>"application/json", "User-Agent"=>"ascli", "Authorization"=>"🔑"}, :json_params=>{"title"=>"Performance-Test-18958-2024-02-08-UTC-TIME-20:44:52", "recipients"=>[{"name"=>"Perf_Tests", "recipient_type"=>"shared_inbox"}], "private_recipients"=>[], "release_policy"=>"now", "ear_enabled"=>false, "obfuscation_enabled"=>false, "notify_on_upload"=>false, "notified_on_upload"=>[], "notify_on_download"=>false, "notified_on_download"=>[], "notify_on_receipt"=>false, "notified_on_receipt"=>[{"name"=>"andre.merten@ibm.com", "recipient_type"=>"user"}], "prevent_http_download"=>false}}
D, [2024-02-08T20:44:53.475124 #2509891] DEBUG -- : call_data = {:base_url=>"https://faspex5-dev.asperaqa.us/aspera/faspex/api/v5", :auth=>{:type=>:oauth2, :base_url=>"https://faspex5-dev.asperaqa.us/aspera/faspex/auth", :grant_method=>:jwt, :client_id=>"766b98ff-64e7-4f09-983e-95009024d29b", :jwt=>{:payload=>{:iss=>"766b98ff-64e7-4f09-983e-95009024d29b", :aud=>"766b98ff-64e7-4f09-983e-95009024d29b", :sub=>"user:andre.merten@ibm.com"}, :private_key_obj=>#<OpenSSL::PKey::RSA:0x00007f397ef71250 oid=rsaEncryption>, :headers=>{:typ=>"JWT"}}}, :not_auth_codes=>["401"], :operation=>"POST", :subpath=>"packages/10917/transfer_spec/upload", :headers=>{"Accept"=>"application/json", "User-Agent"=>"ascli", "Authorization"=>"🔑"}, :url_params=>{:transfer_type=>"connect"}, :json_params=>{:paths=>["data_5206"]}}
	from /usr/local/rvm/gems/ruby-3.1.2/gems/aspera-cli-4.15.0/bin/ascli:38:in `<top (required)>'
	from /usr/local/rvm/gems/ruby-3.1.2/bin/ascli:25:in `load'
	from /usr/local/rvm/gems/ruby-3.1.2/bin/ascli:25:in `<main>'
```

**Comment by laurent-martin** [comment]
Yes, you found a bug !
will be fixed in next version...

**Comment by laurent-martin** [comment]
beta with fix:
https://ibm.biz/aspera-cli-beta

**Comment by dremerten** [comment]
Installed beta gem above. Transfer is still failing with the following:
```
D, [2024-02-10T16:38:51.509432 #2530229] DEBUG -- : ignore cert? ["wss-hsts443.asperaqa.us", 443]
D, [2024-02-10T16:38:51.509775 #2530229] DEBUG -- : file_list (json)=
[
  "data_6667"
]
D, [2024-02-10T16:38:51.509957 #2530229] DEBUG -- : --file-list=
data_6667
D, [2024-02-10T16:38:51.510026 #2530229] DEBUG -- : ascp args: {:args=>[], :env=>{}, :ascp_version=>:ascp}
D, [2024-02-10T16:38:51.510133 #2530229] DEBUG -- : add_env_args: ENV={"ASPERA_SCP_COOKIE"=>"aspera.faspex20:u:4b21166c-f527-4994-a37c-0aeeeb4de89a:YW5kcmUubWVydGVuQGlibS5jb20:eyJfcGtnX3V1aWQiOiJhNzRlYTI3YS0wYmJhLTQ1YzEtOWI1OC1hOWY0ZjY2NzNiNjciLCJfcGtnX25hbWUiOiJQZXJmb3JtYW5jZS1UZXN0LTE3MDUxLTIwMjQtMDItMTAtVVRDLVRJTUUtMTY6Mzg6NTAiLCJfY3JlYXRlZF91dGMiOiIyMDI0LTAyLTEwVDE2OjM4OjUwLjkxNloiLCJfZHJvcGJveF9uYW1lIjoiUGVyZl9UZXN0cyJ9:UGVyZm9ybWFuY2UtVGVzdC0xNzA1MS0yMDI0LTAyLTEwLVVUQy1USU1FLTE2OjM4OjUw", "ASPERA_SCP_TOKEN"=>"🔑"}, ARGS=["--ws-connect", "-c", "aes256gcm", "-d", "--mode", "send", "--policy", "fair", "--host", "wss-hsts443.asperaqa.us", "--user", "faspex", "-P", "443", "--tags64", "eyJhc3BlcmEiOnsiZmFzcGV4Ijp7ImY1X3hmZXJfaWQiOiI0YjIxMTY2Yy1mNTI3LTQ5OTQtYTM3Yy0wYWVlZWI0ZGU4OWEiLCJudW1fcmVjaXBpZW50cyI6MSwiZHJvcGJveCI6IlBlcmZfVGVzdHMiLCJyZWNpcGllbnRzIjp7fSwibWV0YWRhdGEiOnsiX3BrZ191dWlkIjoiYTc0ZWEyN2EtMGJiYS00NWMxLTliNTgtYTlmNGY2NjczYjY3IiwiX3BrZ19uYW1lIjoiUGVyZm9ybWFuY2UtVGVzdC0xNzA1MS0yMDI0LTAyLTEwLVVUQy1USU1FLTE2OjM4OjUwIiwiX2NyZWF0ZWRfdXRjIjoiMjAyNC0wMi0xMFQxNjozODo1MC45MTZaIiwiX2Ryb3Bib3hfbmFtZSI6IlBlcmZfVGVzdHMifSwiX3BrZ19pZCI6MTA5MTh9LCJ4ZmVyX2lkIjoiNjQ4ZTI2NzEtMzZjMS00NTI4LWI4ZWUtY2I3MWE4MjYzNWFiIiwieGZlcl9yZXRyeSI6MzYwMH19", "-l", "500000", "-m", "0", "--dest64", "--file-list=/root/.aspera/ascli/filelists/934cd1cc-52a2-48fa-97ed-3d8871922ad6", "L1BlcmZvcm1hbmNlLVRlc3QtMTcwNTEtMjAyNC0wMi0xMC1VVEMtVElNRS0xNl8zOF81MCAtIGE3NGVhMjdhLTBiYmEtNDVjMS05YjU4LWE5ZjRmNjY3M2I2Ny5hc3BlcmEtcGFja2FnZS9QS0cgLSBQZXJmb3JtYW5jZS1UZXN0LTE3MDUxLTIwMjQtMDItMTAtVVRDLVRJTUUtMTZfMzhfNTAv"]
D, [2024-02-10T16:38:51.510541 #2530229] DEBUG -- : Starting single session thread
D, [2024-02-10T16:38:51.510665 #2530229] DEBUG -- : wait_for_transfers_completion
D, [2024-02-10T16:38:51.510719 #2530229] DEBUG -- : join #<Thread:0x00007f49e5524c08 /usr/local/rvm/gems/ruby-3.1.2/gems/aspera-cli-4.16.0.pre.202402091458/lib/aspera/fasp/agent_direct.rb:98 run>
D, [2024-02-10T16:38:51.511468 #2530229] DEBUG -- : ENTER (transfer)
D, [2024-02-10T16:38:51.511534 #2530229] DEBUG -- : retries=7
D, [2024-02-10T16:38:51.511579 #2530229] DEBUG -- : transfer starting
D, [2024-02-10T16:38:51.511667 #2530229] DEBUG -- : env_args={:args=>["-q", "--ws-connect", "-c", "aes256gcm", "-d", "--mode", "send", "--policy", "fair", "--host", "wss-hsts443.asperaqa.us", "--user", "faspex", "-P", "443", "--tags64", "eyJhc3BlcmEiOnsiZmFzcGV4Ijp7ImY1X3hmZXJfaWQiOiI0YjIxMTY2Yy1mNTI3LTQ5OTQtYTM3Yy0wYWVlZWI0ZGU4OWEiLCJudW1fcmVjaXBpZW50cyI6MSwiZHJvcGJveCI6IlBlcmZfVGVzdHMiLCJyZWNpcGllbnRzIjp7fSwibWV0YWRhdGEiOnsiX3BrZ191dWlkIjoiYTc0ZWEyN2EtMGJiYS00NWMxLTliNTgtYTlmNGY2NjczYjY3IiwiX3BrZ19uYW1lIjoiUGVyZm9ybWFuY2UtVGVzdC0xNzA1MS0yMDI0LTAyLTEwLVVUQy1USU1FLTE2OjM4OjUwIiwiX2NyZWF0ZWRfdXRjIjoiMjAyNC0wMi0xMFQxNjozODo1MC45MTZaIiwiX2Ryb3Bib3hfbmFtZSI6IlBlcmZfVGVzdHMifSwiX3BrZ19pZCI6MTA5MTh9LCJ4ZmVyX2lkIjoiNjQ4ZTI2NzEtMzZjMS00NTI4LWI4ZWUtY2I3MWE4MjYzNWFiIiwieGZlcl9yZXRyeSI6MzYwMH19", "-l", "500000", "-m", "0", "--dest64", "--file-list=/root/.aspera/ascli/filelists/934cd1cc-52a2-48fa-97ed-3d8871922ad6", "L1BlcmZvcm1hbmNlLVRlc3QtMTcwNTEtMjAyNC0wMi0xMC1VVEMtVElNRS0xNl8zOF81MCAtIGE3NGVhMjdhLTBiYmEtNDVjMS05YjU4LWE5ZjRmNjY3M2I2Ny5hc3BlcmEtcGFja2FnZS9QS0cgLSBQZXJmb3JtYW5jZS1UZXN0LTE3MDUxLTIwMjQtMDItMTAtVVRDLVRJTUUtMTZfMzhfNTAv"], :env=>{"ASPERA_SCP_COOKIE"=>"aspera.faspex20:u:4b21166c-f527-4994-a37c-0aeeeb4de89a:YW5kcmUubWVydGVuQGlibS5jb20:eyJfcGtnX3V1aWQiOiJhNzRlYTI3YS0wYmJhLTQ1YzEtOWI1OC1hOWY0ZjY2NzNiNjciLCJfcGtnX25hbWUiOiJQZXJmb3JtYW5jZS1UZXN0LTE3MDUxLTIwMjQtMDItMTAtVVRDLVRJTUUtMTY6Mzg6NTAiLCJfY3JlYXRlZF91dGMiOiIyMDI0LTAyLTEwVDE2OjM4OjUwLjkxNloiLCJfZHJvcGJveF9uYW1lIjoiUGVyZl9UZXN0cyJ9:UGVyZm9ybWFuY2UtVGVzdC0xNzA1MS0yMDI0LTAyLTEwLVVUQy1USU1FLTE2OjM4OjUw", "ASPERA_SCP_TOKEN"=>"🔑"}, :ascp_version=>:ascp}
D, [2024-02-10T16:38:51.512333 #2530229] DEBUG -- : Found /root/.aspera/sdk
D, [2024-02-10T16:38:51.513264 #2530229] DEBUG -- : ascp_path=/root/.aspera/sdk/ascp
D, [2024-02-10T16:38:51.513423 #2530229] DEBUG -- : execute: ASPERA_SCP_COOKIE=aspera.faspex20:u:4b21166c-f527-4994-a37c-0aeeeb4de89a:YW5kcmUubWVydGVuQGlibS5jb20:eyJfcGtnX3V1aWQiOiJhNzRlYTI3YS0wYmJhLTQ1YzEtOWI1OC1hOWY0ZjY2NzNiNjciLCJfcGtnX25hbWUiOiJQZXJmb3JtYW5jZS1UZXN0LTE3MDUxLTIwMjQtMDItMTAtVVRDLVRJTUUtMTY6Mzg6NTAiLCJfY3JlYXRlZF91dGMiOiIyMDI0LTAyLTEwVDE2OjM4OjUwLjkxNloiLCJfZHJvcGJveF9uYW1lIjoiUGVyZl9UZXN0cyJ9:UGVyZm9ybWFuY2UtVGVzdC0xNzA1MS0yMDI0LTAyLTEwLVVUQy1USU1FLTE2OjM4OjUw ASPERA_SCP_TOKEN=🔑 /root/.aspera/sdk/ascp -M 34297 -q --ws-connect -c aes256gcm -d --mode send --policy fair --host wss-hsts443.asperaqa.us --user faspex -P 443 --tags64 eyJhc3BlcmEiOnsiZmFzcGV4Ijp7ImY1X3hmZXJfaWQiOiI0YjIxMTY2Yy1mNTI3LTQ5OTQtYTM3Yy0wYWVlZWI0ZGU4OWEiLCJudW1fcmVjaXBpZW50cyI6MSwiZHJvcGJveCI6IlBlcmZfVGVzdHMiLCJyZWNpcGllbnRzIjp7fSwibWV0YWRhdGEiOnsiX3BrZ191dWlkIjoiYTc0ZWEyN2EtMGJiYS00NWMxLTliNTgtYTlmNGY2NjczYjY3IiwiX3BrZ19uYW1lIjoiUGVyZm9ybWFuY2UtVGVzdC0xNzA1MS0yMDI0LTAyLTEwLVVUQy1USU1FLTE2OjM4OjUwIiwiX2NyZWF0ZWRfdXRjIjoiMjAyNC0wMi0xMFQxNjozODo1MC45MTZaIiwiX2Ryb3Bib3hfbmFtZSI6IlBlcmZfVGVzdHMifSwiX3BrZ19pZCI6MTA5MTh9LCJ4ZmVyX2lkIjoiNjQ4ZTI2NzEtMzZjMS00NTI4LWI4ZWUtY2I3MWE4MjYzNWFiIiwieGZlcl9yZXRyeSI6MzYwMH19 -l 500000 -m 0 --dest64 --file-list\=/root/.aspera/ascli/filelists/934cd1cc-52a2-48fa-97ed-3d8871922ad6 L1BlcmZvcm1hbmNlLVRlc3QtMTcwNTEtMjAyNC0wMi0xMC1VVEMtVElNRS0xNl8zOF81MCAtIGE3NGVhMjdhLTBiYmEtNDVjMS05YjU4LWE5ZjRmNjY3M2I2Ny5hc3BlcmEtcGFja2FnZS9QS0cgLSBQZXJmb3JtYW5jZS1UZXN0LTE3MDUxLTIwMjQtMDItMTAtVVRDLVRJTUUtMTZfMzhfNTAv
D, [2024-02-10T16:38:51.516658 #2530229] DEBUG -- : spawned pid 2530231
D, [2024-02-10T16:38:51.516762 #2530229] DEBUG -- : before select, timeout: 2
D, [2024-02-10T16:38:51.522661 #2530229] DEBUG -- : after select, before accept
D, [2024-02-10T16:38:51.522745 #2530229] DEBUG -- : after accept
D, [2024-02-10T16:38:51.689787 #2530229] DEBUG -- : ascp failed with code
E, [2024-02-10T16:38:51.689980 #2530229] ERROR -- : Transfer thread error: RuntimeError:
unexpected last event type: INIT:
/usr/local/rvm/gems/ruby-3.1.2/gems/aspera-cli-4.16.0.pre.202402091458/lib/aspera/fasp/agent_direct.rb:267:in `start_transfer_with_args_env'
/usr/local/rvm/gems/ruby-3.1.2/gems/aspera-cli-4.16.0.pre.202402091458/lib/aspera/fasp/agent_direct.rb:352:in `block in transfer_thread_entry'
/usr/local/rvm/gems/ruby-3.1.2/gems/aspera-cli-4.16.0.pre.202402091458/lib/aspera/fasp/resume_policy.rb:46:in `block in execute_with_resume'
/usr/local/rvm/gems/ruby-3.1.2/gems/aspera-cli-4.16.0.pre.202402091458/lib/aspera/fasp/resume_policy.rb:42:in `loop'
/usr/local/rvm/gems/ruby-3.1.2/gems/aspera-cli-4.16.0.pre.202402091458/lib/aspera/fasp/resume_policy.rb:42:in `execute_with_resume'
/usr/local/rvm/gems/ruby-3.1.2/gems/aspera-cli-4.16.0.pre.202402091458/lib/aspera/fasp/agent_direct.rb:351:in `transfer_thread_entry'
/usr/local/rvm/gems/ruby-3.1.2/gems/aspera-cli-4.16.0.pre.202402091458/lib/aspera/fasp/agent_direct.rb:98:in `block in start_transfer'
D, [2024-02-10T16:38:51.690215 #2530229] DEBUG -- : EXIT (transfer)
D, [2024-02-10T16:38:51.690283 #2530229] DEBUG -- : all transfers joined
D, [2024-02-10T16:38:51.690394 #2530229] DEBUG -- : (value) get notify_to=
ERROR: Other(RuntimeError): unexpected last event type: INIT
/usr/local/rvm/gems/ruby-3.1.2/gems/aspera-cli-4.16.0.pre.202402091458/lib/aspera/fasp/agent_direct.rb:267:in `start_transfer_with_args_env': unexpected last event type: INIT (RuntimeError)
	from /usr/local/rvm/gems/ruby-3.1.2/gems/aspera-cli-4.16.0.pre.202402091458/lib/aspera/fasp/agent_direct.rb:352:in `block in transfer_thread_entry'
	from /usr/local/rvm/gems/ruby-3.1.2/gems/aspera-cli-4.16.0.pre.202402091458/lib/aspera/fasp/resume_policy.rb:46:in `block in execute_with_resume'
	from /usr/local/rvm/gems/ruby-3.1.2/gems/aspera-cli-4.16.0.pre.202402091458/lib/aspera/fasp/resume_policy.rb:42:in `loop'
	from /usr/local/rvm/gems/ruby-3.1.2/gems/aspera-cli-4.16.0.pre.202402091458/lib/aspera/fasp/resume_policy.rb:42:in `execute_with_resume'
	from /usr/local/rvm/gems/ruby-3.1.2/gems/aspera-cli-4.16.0.pre.202402091458/lib/aspera/fasp/agent_direct.rb:351:in `transfer_thread_entry'
	from /usr/local/rvm/gems/ruby-3.1.2/gems/aspera-cli-4.16.0.pre.202402091458/lib/aspera/fasp/agent_direct.rb:98:in `block in start_transfer'
	```

**Comment by laurent-martin** [comment]
I have placed a new beta here: https://ibm.biz/aspera-cli-beta
not sure if it fixes this, I'll need to test more next week.

**Comment by laurent-martin** [comment]
The last error: `unexpected last event type: INIT`, comes from the fact that ascli expects the last event on ascp management port (just before it gets closed) to be either `DONE` or `ERROR`, but actually it gets onlt the initial `INIT`.
I need to reproduce that..
