### ISSUE TITLE
Runtime error - unexpected last event type: INIT

### ISSUE THREAD

**Issue by lebedov** [IBM/aspera-cli#139]
I'm attempting to use aspera-cli 4.16.0 with ruby 3.0.0 (installed via rvm) on an Ubuntu 18.04.6 environment hosted as a Docker image on AWS to download a faspx package from TCIA using the following invocation:

```
ascli faspex5 packages receive --url='https://faspex.cancerimagingarchive.net/aspera/faspex/public/package?context=eyJyZXNvdXJjZSI6InBhY2thZ2VzIiwidHlwZSI6ImV4dGVybmFsX2Rvd25sb2FkX3BhY2thZ2UiLCJpZCI6Ijc0MSIsInBhc3Njb2RlIjoiYmM0NmFjYzJjZTg2MTdhYTQ3N2JhMmY3ZThmZjk3YzUxNDY1ZTIzZiIsInBhY2thZ2VfaWQiOiI3NDEiLCJlbWFpbCI6ImhlbHBAY2FuY2VyaW1hZ2luZ2FyY2hpdmUubmV0In0=' --log-level=debug
```

Accessing the above URI from a web browser (with the Aspera extension installed) seems to work, so I'm pretty sure the package is available for download. The above invocation of ascli, however, fails with an "unexpected last event type: INIT" runtime error as follows (last few lines of log before error included):

```
D, [2024-04-09T19:12:18.994540 #45513] DEBUG -- : execute: ASPERA_SCP_COOKIE=aspera.faspex20:d:385abc7c-830e-4668-b86c-31b83540c3b9:aGVscEBjYW5jZXJpbWFnaW5nYXJjaGl2ZS5uZXQ:eyJfcGtnX3V1aWQiOiIzZjBlZTY1My03ZjU2LTQ4YjItYTI0Yy1iMmVjNTExNzUxM2IiLCJfcGtnX25hbWUiOiJIdW5nYXJpYW4tQ29sb3JlY3RhbC1TY3JlZW5pbmdfdjIiLCJfY3JlYXRlZF91dGMiOiIyMDIzLTEyLTA2VDIwOjMyOjQxLjMwNloifQ:SHVuZ2FyaWFuLUNvbG9yZWN0YWwtU2NyZWVuaW5nX3Yy ASPERA_SCP_TOKEN=🔑 /home/ubuntu/.aspera/sdk/ascp -M 40617 -q -i /home/ubuntu/.aspera/sdk/aspera_bypass_rsa.pem -i /home/ubuntu/.aspera/sdk/aspera_bypass_dsa.pem -c aes128 -d --mode recv -O 33001 --policy fair --host hsts.uams.edu --user faspex -P 33001 --tags64 eyJhc3BlcmEiOnsiZmFzcGV4Ijp7ImY1X3hmZXJfaWQiOiIzODVhYmM3Yy04MzBlLTQ2NjgtYjg2Yy0zMWI4MzU0MGMzYjkiLCJudW1fcmVjaXBpZW50cyI6MSwiZG93bmxvYWRlciI6eyJuYW1lIjoiaGVscEBjYW5jZXJpbWFnaW5nYXJjaGl2ZS5uZXQiLCJmaXJzdF9uYW1lIjoiaGVscEBjYW5jZXJpbWFnaW5nYXJjaGl2ZS5uZXQiLCJsYXN0X25hbWUiOiIoZXh0ZXJuYWwgZW1haWwpIiwiZW1haWwiOiJoZWxwQGNhbmNlcmltYWdpbmdhcmNoaXZlLm5ldCJ9LCJyZXF1ZXN0b3IiOnsibmFtZSI6Im5hdGFzaGEiLCJmaXJzdF9uYW1lIjoiTmF0YXNoYSIsImxhc3RfbmFtZSI6Ikhvbm9taWNobCIsImVtYWlsIjoibmhvbm9taWNobEB1YW1zLmVkdSJ9LCJtZXRhZGF0YSI6eyJfcGtnX3V1aWQiOiIzZjBlZTY1My03ZjU2LTQ4YjItYTI0Yy1iMmVjNTExNzUxM2IiLCJfcGtnX25hbWUiOiJIdW5nYXJpYW4tQ29sb3JlY3RhbC1TY3JlZW5pbmdfdjIiLCJfY3JlYXRlZF91dGMiOiIyMDIzLTEyLTA2VDIwOjMyOjQxLjMwNloifSwiX3BrZ19pZCI6NzQxfSwieGZlcl9pZCI6ImExODRiZmViLTA4Y2QtNDMzNC1iNjZlLTRmOTVhOTBlYWVhMyIsInhmZXJfcmV0cnkiOjM2MDB9fQ\=\= -l 2000000 -m 0 --dest64 --file-list\=/home/ubuntu/.aspera/ascli/filelists/5f90ceca-4658-4c3b-994f-4feed21c2a15 Lg\=\=
D, [2024-04-09T19:12:19.010448 #45513] DEBUG -- : spawned pid 45515
D, [2024-04-09T19:12:19.010491 #45513] DEBUG -- : progress: pre_start  waiting for ascp
D, [2024-04-09T19:12:19.010621 #45513] DEBUG -- : before select, timeout: 2--= 0% 0 Mbps  ETA: ??:??:??
D, [2024-04-09T19:12:19.018629 #45513] DEBUG -- : after select, before accept
D, [2024-04-09T19:12:19.018676 #45513] DEBUG -- : after accept
D, [2024-04-09T19:12:19.111404 #45513] DEBUG -- : progress: session_start a4689592-ca54-4ce3-b620-c246e241630e 
D, [2024-04-09T19:28:33.270962 #45513] DEBUG -- : management io closed=---=--- 0% 0 Mbps  ETA: ??:??:??
E, [2024-04-09T19:28:33.272130 #45513] ERROR -- : ascp failed: pid 45515 exit 1
E, [2024-04-09T19:28:33.272252 #45513] ERROR -- : Transfer thread error: RuntimeError:
unexpected last event type: INIT:
/home/ubuntu/.rvm/gems/ruby-3.0.0/gems/aspera-cli-4.16.0/lib/aspera/fasp/agent_direct.rb:268:in `start_transfer_with_args_env'
/home/ubuntu/.rvm/gems/ruby-3.0.0/gems/aspera-cli-4.16.0/lib/aspera/fasp/agent_direct.rb:353:in `block in transfer_thread_entry'
/home/ubuntu/.rvm/gems/ruby-3.0.0/gems/aspera-cli-4.16.0/lib/aspera/fasp/resume_policy.rb:46:in `block in execute_with_resume'
/home/ubuntu/.rvm/gems/ruby-3.0.0/gems/aspera-cli-4.16.0/lib/aspera/fasp/resume_policy.rb:42:in `loop'
/home/ubuntu/.rvm/gems/ruby-3.0.0/gems/aspera-cli-4.16.0/lib/aspera/fasp/resume_policy.rb:42:in `execute_with_resume'
/home/ubuntu/.rvm/gems/ruby-3.0.0/gems/aspera-cli-4.16.0/lib/aspera/fasp/agent_direct.rb:352:in `transfer_thread_entry'
/home/ubuntu/.rvm/gems/ruby-3.0.0/gems/aspera-cli-4.16.0/lib/aspera/fasp/agent_direct.rb:98:in `block in start_transfer'
D, [2024-04-09T19:28:33.272369 #45513] DEBUG -- : EXIT (transfer)
D, [2024-04-09T19:28:33.272447 #45513] DEBUG -- : all transfers joined
D, [2024-04-09T19:28:33.272592 #45513] DEBUG -- : (value) get notify_to=
ERROR: Other(RuntimeError): unexpected last event type: INIT
/home/ubuntu/.rvm/gems/ruby-3.0.0/gems/aspera-cli-4.16.0/lib/aspera/fasp/agent_direct.rb:268:in `start_transfer_with_args_env': unexpected last event type: INIT (RuntimeError)
        from /home/ubuntu/.rvm/gems/ruby-3.0.0/gems/aspera-cli-4.16.0/lib/aspera/fasp/agent_direct.rb:353:in `block in transfer_thread_entry'
        from /home/ubuntu/.rvm/gems/ruby-3.0.0/gems/aspera-cli-4.16.0/lib/aspera/fasp/resume_policy.rb:46:in `block in execute_with_resume'
        from /home/ubuntu/.rvm/gems/ruby-3.0.0/gems/aspera-cli-4.16.0/lib/aspera/fasp/resume_policy.rb:42:in `loop'
        from /home/ubuntu/.rvm/gems/ruby-3.0.0/gems/aspera-cli-4.16.0/lib/aspera/fasp/resume_policy.rb:42:in `execute_with_resume'
        from /home/ubuntu/.rvm/gems/ruby-3.0.0/gems/aspera-cli-4.16.0/lib/aspera/fasp/agent_direct.rb:352:in `transfer_thread_entry'
        from /home/ubuntu/.rvm/gems/ruby-3.0.0/gems/aspera-cli-4.16.0/lib/aspera/fasp/agent_direct.rb:98:in `block in start_transfer'
```

Any thoughts as to what could be going on?

**Comment by laurent-martin** [comment]
It seems that ascp exits unexpectedly (exit 1)
You can enable transfer logs with argument:
`--transfer-info=@json:'{"ascp_args":["-DDL-"]}'`
and see if there is more details.
I tried the command on laptop, and it worked.

**Comment by laurent-martin** [comment]
You may check, from within the container (podman exec -it mycontainer bash) if you get the SSH banner on `hsts.uams.edu`.
Something like: `telnet hsts.uams.edu 33001` or `echo | curl -vv telnet://hsts.uams.edu:33001`
It should display `SSH-2.0-OpenSSH_7.4`, validating if TCP connection works at least.

**Comment by lebedov** [comment]
I don't get the banner. Must be something having to do with corporate firewall routing which is being done for the containers I'm using. A colleague who tried downloading a different faspex package on TCIA from a similar container in the past claimed he was able to successfully download it after installing ruby, ascli, etc. as I did, though, so I'm not sure what could have been different about his scenario.

**Comment by laurent-martin** [comment]
I do get a prompt with `ssh -v hsts.uams.edu -p 33001` which confirms that the problem is in the environment.

I can reproduce thje error like this:

1- start a tcp listener locally in a terminal: `nc -l 12345`
2- start a fake transfer in another terminal: `ascli server --url=ssh://localhost:12345 --username=x --password=y down x`
3- the listener sends an SSH banner in the first terminal, I copy it, and send it back in the listener, then ascli/ascp sends some SSH information, and I hit enter a few times: protocol error
4- ascli displays the same error: `unexpected last event type: INIT`
