### ISSUE TITLE
4.6 : if option 'use_product' is set, then ascli fails with "Undefined path to SDK"

### ISSUE THREAD

**Issue by laurent-martin** [IBM/aspera-cli#64]
```
ascli --use-product='Aspera Connect'
.../gems/aspera-cli-4.6.0/lib/aspera/fasp/installation.rb:293:in `folder_path': Undefined path to SDK (RuntimeError)
	from .../gems/aspera-cli-4.6.0/lib/aspera/fasp/installation.rb:68:in `installed_products'
	from .../gems/aspera-cli-4.6.0/lib/aspera/fasp/installation.rb:54:in `use_ascp_from_product'
	from .../gems/aspera-cli-4.6.0/lib/aspera/cli/plugins/config.rb:337:in `option_use_product='
	from .../gems/aspera-cli-4.6.0/lib/aspera/cli/manager.rb:36:in `value='
	from .../gems/aspera-cli-4.6.0/lib/aspera/cli/manager.rb:248:in `set_option'
	from .../gems/aspera-cli-4.6.0/lib/aspera/cli/manager.rb:342:in `block in add_opt_simple'
	from .../lib/ruby/3.0.0/optparse.rb:1591:in `block in parse_in_order'
	from .../lib/ruby/3.0.0/optparse.rb:1577:in `catch'
	from .../lib/ruby/3.0.0/optparse.rb:1577:in `parse_in_order'
	from .../lib/ruby/3.0.0/optparse.rb:1571:in `order!'
	from .../lib/ruby/3.0.0/optparse.rb:1668:in `permute!'
	from .../lib/ruby/3.0.0/optparse.rb:1693:in `parse!'
	from .../gems/aspera-cli-4.6.0/lib/aspera/cli/manager.rb:442:in `parse_options!'
	from .../gems/aspera-cli-4.6.0/lib/aspera/cli/plugins/config.rb:151:in `initialize'
	from .../gems/aspera-cli-4.6.0/lib/aspera/cli/main.rb:84:in `new'
	from .../gems/aspera-cli-4.6.0/lib/aspera/cli/main.rb:84:in `initialize'
	from .../gems/aspera-cli-4.6.0/bin/ascli:9:in `new'
	from .../gems/aspera-cli-4.6.0/bin/ascli:9:in `<top (required)>'
	from .../bin/ascli:23:in `load'
	from .../bin/ascli:23:in `<main>'
```
workaround: do not use option `--use-product=` and remove parameter `use_product` from `$HOME/.aspera/ascli/config.yaml`

Instead, you can use option `--ascp-path=` or just install the SDK:

```
ascli conf ascp install
```

**Comment by laurent-martin** [comment]
fixed in next version
